## Constants

GAME_RUNNING = 0
GAME_FINISHED = 1

LEVEL_NAMES = ['forest', 'village']

START_LEVEL = 'forest'

TILE_SIZE = 15

INVENTORY_WIDTH = 16

MAP_WIDTH = 33
MAP_HEIGHT = 33

SCREEN_WIDTH_TILES = MAP_WIDTH + INVENTORY_WIDTH * 2
SCREEN_HEIGHT_TILES = MAP_HEIGHT + 1

SCREEN_WIDTH = TILE_SIZE * SCREEN_WIDTH_TILES
SCREEN_HEIGHT = TILE_SIZE * SCREEN_HEIGHT_TILES

FRAMERATE = 7

BORDER_WIDTH = 2

COLOR_RED = 0
COLOR_GREEN = 1
COLOR_BLUE = 2
COLOR_WHITE = 3
COLOR_GRAY = 4
COLOR_BROWN = 5
COLOR_YELLOW = 6


COLORS = [(COLOR_RED, 'red', (255, 0, 0)),
          (COLOR_GREEN, 'green', (0, 255, 0)),
          (COLOR_BLUE, 'blue', (0, 0, 255)),
          (COLOR_WHITE, 'white', (255, 255, 255)),
          (COLOR_GRAY, 'gray', (125, 125, 125)),
          (COLOR_BROWN, 'brown', (102, 51, 0)),
          (COLOR_YELLOW, 'yellow', (204, 153, 0))]
