## Constants

GAME_RUNNING = 0
GAME_FINISHED = 1

LEVEL_NAMES = ['forest', 'village']

START_LEVEL = 'forest'

TILE_SIZE = 15

MAP_WIDTH = 33
MAP_HEIGHT = 33

SCREEN_WIDTH_TILES = MAP_WIDTH
SCREEN_HEIGHT_TILES = MAP_HEIGHT + 1

SCREEN_WIDTH = TILE_SIZE * SCREEN_WIDTH_TILES
SCREEN_HEIGHT = TILE_SIZE * SCREEN_HEIGHT_TILES

FRAMERATE = 7

BORDER_WIDTH = 2

