## Constants

GAME_RUNNING = 0
GAME_FINISHED = 1

LEVEL_NAMES = ['forest']

START_LEVEL = 'forest'

TILE_SIZE = 15
SCREEN_WIDTH_TILES = 33
SCREEN_HEIGHT_TILES = 33

SCREEN_WIDTH = TILE_SIZE * SCREEN_WIDTH_TILES
SCREEN_HEIGHT = TILE_SIZE * SCREEN_HEIGHT_TILES
